### ISSUE TITLE
Show only panel on error

### ISSUE THREAD

**Issue by trbjo** [mitranim/sublime-fmt#9]
It is annoying that the bottom panel pops up even if nothing is changed in the buffer. Is it possible to change the behavior so that it only pops up if something changes?

**Comment by mitranim** [comment]
The panel is only for errors. Screenshot please?

**Comment by trbjo** [comment]
![image](https://user-images.githubusercontent.com/26080212/179517512-cc6ce85a-d75a-42d0-b986-77462b68e1a1.png)

**Comment by mitranim** [comment]
This is `stderr` output from Black, which is considered an error by Fmt. Fmt expects the subprocess (Black in this case) to output file content over stdin, or error over stderr, not both. From #8, it sounds like you're passing a file name to format _after save_. Fmt invokes the CLI tool _before save_ and communicates over stdio. You need to configure Black to use stdio without a file name.

**Comment by mitranim** [comment]
Pushed an update. Fmt will ignore "informational" output over stderr when the subprocess successfully produces output over stdout.

**Comment by mitranim** [comment]
Should be fixed by 44389e441e6c6fbe8e8f2195d83eda294b658705.
